apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: ${{ name }}-env-secrets
    creationPolicy: Owner
  data:
    {%- if needsDatabase %}
    - secretKey: DATABASE_PASSWORD
      remoteRef:
        key: secret/data/${{ project }}/${{ name }}
        property: db-password
    {%- endif %}
    {%- if needsCache %}
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: secret/data/${{ project }}/${{ name }}
        property: redis-password
    {%- endif %}
