apiVersion: v1
kind: Service
metadata:
  name: ${{ name }}
  labels:
    app: ${{ name }}
spec:
  ports:
    - port: ${{ port }}
      targetPort: ${{ port }}
      protocol: TCP
      name: http
  selector:
    app: ${{ name }}
