apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ${{ name }}-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: openbao-store
    kind: ClusterSecretStore
  target:
    name: ${{ name }}-env-secrets
    creationPolicy: Owner
  data:
    - secretKey: LITELLM_API_KEY
      remoteRef:
        key: secret/data/${{ project }}/litellm
        property: api-key
    - secretKey: LANGSMITH_API_KEY
      remoteRef:
        key: secret/data/${{ project }}/langsmith
        property: api-key
