server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,prometheus

spring:
  security:
    user:
      name: user
      password: ${SECURITY_USER_PASSWORD:password}
