replicaCount: 1
image:
  repository: ghcr.io/polfenollar/veyor-quoting
  pullPolicy: IfNotPresent
  tag: "latest"
service:
  type: ClusterIP
  port: 50051
resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
livenessProbe:
  grpc:
    port: 50051
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  grpc:
    port: 50051
  initialDelaySeconds: 3
  periodSeconds: 5
env: {}
